apiVersion: v1
kind: ConfigMap
metadata:
  name: api-order-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://db-order-svc:5432/order_db
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-svc:9092
  EXTERNAL_API_PRODUCT_SERVICE_URL: http://api-produtos-svc:8080
  EXTERNAL_API_CUSTOMER_SERVICE_URL: http://api-clientes-svc:8080
  JWT_EXPIRATION_MINUTES: "15"
