apiVersion: v1
kind: Service
metadata:
  name: api-staff-svc
spec:
  type: NodePort
  selector:
    app: api-staff
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30085
